/**
 * Stacker's sound, synthesized in the browser.
 *
 * Every sound here is generated by Web Audio at runtime — no files, no
 * licensing surface, a couple of kilobytes of code instead of thirty
 * megabytes of assets. It also suits the game: sounds are consequences of
 * engine events, so they can be triggered exactly where those events happen
 * and pitched by how big they were.
 *
 * (If you later want a real recorded soundtrack, `playMusic` is the one place
 * to change: point it at an <audio> element for a track you own or have a
 * licence for. Everything else can stay.)
 *
 * The audio context is created lazily on the first user gesture, because
 * browsers refuse to start one otherwise.
 */

export type Sfx =
  | 'move' | 'rotate' | 'lock' | 'hold' | 'drop'
  | 'clear1' | 'clear2' | 'clear3' | 'clear4'
  | 'spin' | 'combo' | 'garbage' | 'danger' | 'topout' | 'win';

let ctx: AudioContext | null = null;
let master: GainNode | null = null;
let musicGain: GainNode | null = null;
let sfxGain: GainNode | null = null;
let musicTimer: ReturnType<typeof setInterval> | null = null;
let musicStep = 0;

const STORAGE_KEY = 'obelisk-dex/stacker/audio';

export interface AudioPrefs {
  muted: boolean;
  music: boolean;
}

export function loadPrefs(): AudioPrefs {
  if (typeof localStorage === 'undefined') return { muted: false, music: true };
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (!raw) return { muted: false, music: true };
    const parsed = JSON.parse(raw) as Partial<AudioPrefs>;
    return { muted: parsed.muted === true, music: parsed.music !== false };
  } catch {
    return { muted: false, music: true };
  }
}

export function savePrefs(prefs: AudioPrefs): void {
  if (typeof localStorage === 'undefined') return;
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(prefs));
  } catch {
    /* a full quota is not worth breaking the game over */
  }
}

/** Start (or resume) the audio graph. Must be called from a user gesture. */
export function ensureAudio(): boolean {
  if (typeof window === 'undefined') return false;
  const Ctor = window.AudioContext
    ?? (window as unknown as { webkitAudioContext?: typeof AudioContext }).webkitAudioContext;
  if (!Ctor) return false;

  if (!ctx) {
    ctx = new Ctor();
    master = ctx.createGain();
    master.gain.value = 0.5;
    master.connect(ctx.destination);

    musicGain = ctx.createGain();
    musicGain.gain.value = 0.16;
    musicGain.connect(master);

    sfxGain = ctx.createGain();
    sfxGain.gain.value = 0.7;
    sfxGain.connect(master);
  }
  if (ctx.state === 'suspended') void ctx.resume();
  return true;
}

export function setMuted(muted: boolean): void {
  if (!master || !ctx) return;
  master.gain.setTargetAtTime(muted ? 0 : 0.5, ctx.currentTime, 0.02);
}

/* ── voices ───────────────────────────────────────────────────────────── */

function blip(opts: {
  freq: number;
  to?: number;
  duration: number;
  type?: OscillatorType;
  gain?: number;
  delay?: number;
}): void {
  if (!ctx || !sfxGain) return;
  const t0 = ctx.currentTime + (opts.delay ?? 0);
  const osc = ctx.createOscillator();
  const env = ctx.createGain();
  osc.type = opts.type ?? 'square';
  osc.frequency.setValueAtTime(opts.freq, t0);
  if (opts.to !== undefined) osc.frequency.exponentialRampToValueAtTime(Math.max(1, opts.to), t0 + opts.duration);
  env.gain.setValueAtTime(0, t0);
  env.gain.linearRampToValueAtTime(opts.gain ?? 0.3, t0 + 0.008);
  env.gain.exponentialRampToValueAtTime(0.0001, t0 + opts.duration);
  osc.connect(env);
  env.connect(sfxGain);
  osc.start(t0);
  osc.stop(t0 + opts.duration + 0.02);
}

/** Filtered noise — thuds, garbage, impacts. */
function noise(opts: { duration: number; gain?: number; freq?: number; delay?: number }): void {
  if (!ctx || !sfxGain) return;
  const t0 = ctx.currentTime + (opts.delay ?? 0);
  const frames = Math.floor(ctx.sampleRate * opts.duration);
  const buffer = ctx.createBuffer(1, Math.max(1, frames), ctx.sampleRate);
  const data = buffer.getChannelData(0);
  for (let i = 0; i < frames; i++) {
    // Decaying noise, so it reads as an impact rather than a hiss.
    data[i] = (Math.random() * 2 - 1) * (1 - i / frames);
  }
  const src = ctx.createBufferSource();
  src.buffer = buffer;
  const filter = ctx.createBiquadFilter();
  filter.type = 'lowpass';
  filter.frequency.value = opts.freq ?? 800;
  const env = ctx.createGain();
  env.gain.value = opts.gain ?? 0.25;
  src.connect(filter);
  filter.connect(env);
  env.connect(sfxGain);
  src.start(t0);
}

/** Play one of the game's sounds. Silent (and harmless) before `ensureAudio`. */
export function playSfx(sfx: Sfx): void {
  if (!ctx || !sfxGain) return;

  switch (sfx) {
    case 'move':
      blip({ freq: 220, duration: 0.03, type: 'square', gain: 0.08 });
      break;
    case 'rotate':
      blip({ freq: 330, to: 420, duration: 0.05, type: 'triangle', gain: 0.12 });
      break;
    case 'hold':
      blip({ freq: 520, to: 380, duration: 0.08, type: 'triangle', gain: 0.14 });
      break;
    case 'drop':
      blip({ freq: 180, to: 60, duration: 0.09, type: 'sawtooth', gain: 0.16 });
      noise({ duration: 0.06, gain: 0.18, freq: 500 });
      break;
    case 'lock':
      noise({ duration: 0.05, gain: 0.14, freq: 400 });
      break;
    // Clears climb in pitch and length with the line count, so a quad
    // announces itself without needing a caption.
    case 'clear1':
      blip({ freq: 523, to: 784, duration: 0.16, type: 'triangle', gain: 0.22 });
      break;
    case 'clear2':
      blip({ freq: 523, duration: 0.1, type: 'square', gain: 0.2 });
      blip({ freq: 659, duration: 0.16, type: 'square', gain: 0.2, delay: 0.07 });
      break;
    case 'clear3':
      blip({ freq: 523, duration: 0.09, type: 'square', gain: 0.2 });
      blip({ freq: 659, duration: 0.09, type: 'square', gain: 0.2, delay: 0.07 });
      blip({ freq: 784, duration: 0.2, type: 'square', gain: 0.22, delay: 0.14 });
      break;
    case 'clear4':
      // The big one: a rising arpeggio with a shimmer on top.
      [523, 659, 784, 1047].forEach((f, i) => {
        blip({ freq: f, duration: 0.22, type: 'square', gain: 0.22, delay: i * 0.055 });
      });
      blip({ freq: 2093, duration: 0.5, type: 'sine', gain: 0.12, delay: 0.2 });
      break;
    case 'spin':
      blip({ freq: 880, to: 1320, duration: 0.18, type: 'sine', gain: 0.2 });
      blip({ freq: 660, to: 990, duration: 0.22, type: 'triangle', gain: 0.14, delay: 0.03 });
      break;
    case 'combo':
      blip({ freq: 1200, to: 1800, duration: 0.1, type: 'sine', gain: 0.16 });
      break;
    case 'garbage':
      noise({ duration: 0.22, gain: 0.3, freq: 260 });
      blip({ freq: 90, to: 55, duration: 0.24, type: 'sawtooth', gain: 0.2 });
      break;
    case 'danger':
      blip({ freq: 160, to: 120, duration: 0.3, type: 'sawtooth', gain: 0.1 });
      break;
    case 'topout':
      [440, 370, 294, 220].forEach((f, i) => {
        blip({ freq: f, duration: 0.35, type: 'sawtooth', gain: 0.2, delay: i * 0.12 });
      });
      noise({ duration: 0.7, gain: 0.2, freq: 300, delay: 0.1 });
      break;
    case 'win':
      [523, 659, 784, 1047, 1319].forEach((f, i) => {
        blip({ freq: f, duration: 0.4, type: 'triangle', gain: 0.24, delay: i * 0.1 });
      });
      break;
  }
}

/** The clear sound for a given line count and spin, in one call. */
export function playClear(lines: number, spin: boolean, combo: number): void {
  if (spin) playSfx('spin');
  else if (lines >= 4) playSfx('clear4');
  else if (lines === 3) playSfx('clear3');
  else if (lines === 2) playSfx('clear2');
  else if (lines === 1) playSfx('clear1');
  if (combo >= 2) playSfx('combo');
}

/* ── music ────────────────────────────────────────────────────────────── */

/**
 * A generative bed rather than a loop: a bass line under a shifting arpeggio,
 * stepped on a timer. It never repeats exactly, which wears better over a long
 * match than an eight-bar loop, and it costs nothing to ship.
 *
 * Swap this function's body for an <audio> element if you bring your own
 * track — nothing else in the game touches music.
 */
const SCALE = [0, 3, 5, 7, 10]; // minor pentatonic: hard to make sound wrong
const ROOTS = [110, 110, 98, 87.31, 98]; // A, A, G, F, G

export function startMusic(): void {
  if (!ctx || !musicGain || musicTimer) return;
  const stepMs = 150;

  musicTimer = setInterval(() => {
    if (!ctx || !musicGain) return;
    const t = ctx.currentTime;
    const bar = Math.floor(musicStep / 16) % ROOTS.length;
    const root = ROOTS[bar];

    // Bass on the downbeat and the off-beat.
    if (musicStep % 4 === 0) {
      const osc = ctx.createOscillator();
      const env = ctx.createGain();
      osc.type = 'triangle';
      osc.frequency.value = root / 2;
      env.gain.setValueAtTime(0, t);
      env.gain.linearRampToValueAtTime(0.5, t + 0.01);
      env.gain.exponentialRampToValueAtTime(0.001, t + 0.28);
      osc.connect(env);
      env.connect(musicGain);
      osc.start(t);
      osc.stop(t + 0.3);
    }

    // Arpeggio, wandering up and down the scale.
    const degree = SCALE[(musicStep * 3) % SCALE.length];
    const octave = musicStep % 8 < 4 ? 2 : 4;
    const osc = ctx.createOscillator();
    const env = ctx.createGain();
    osc.type = 'square';
    osc.frequency.value = root * octave * Math.pow(2, degree / 12);
    env.gain.setValueAtTime(0, t);
    env.gain.linearRampToValueAtTime(0.12, t + 0.008);
    env.gain.exponentialRampToValueAtTime(0.001, t + 0.14);
    osc.connect(env);
    env.connect(musicGain);
    osc.start(t);
    osc.stop(t + 0.16);

    musicStep += 1;
  }, stepMs);
}

export function stopMusic(): void {
  if (musicTimer) {
    clearInterval(musicTimer);
    musicTimer = null;
  }
}

/** Lift the music a little when things get tense. */
export function setMusicIntensity(danger: number): void {
  if (!ctx || !musicGain) return;
  musicGain.gain.setTargetAtTime(0.12 + Math.min(1, danger) * 0.12, ctx.currentTime, 0.3);
}

/** For tests and teardown. */
export function disposeAudio(): void {
  stopMusic();
  if (ctx) void ctx.close().catch(() => {});
  ctx = null;
  master = null;
  musicGain = null;
  sfxGain = null;
  musicStep = 0;
}
